version: '2'
services:
    apache:
        image: ambientum/php:7.0-apache
        container_name: server-coordinates
        volumes:
          - ../:/var/www/app/public
        ports:
          - "8090:8080"